[build]
  command   = "npm run build"
  publish   = ".next"

[context.production.environment]
  NEXT_PUBLIC_SITE_ENV = "production"
  NEXT_PUBLIC_SITE_URL = "https://pinga.photos"

[context."staging".environment]
  NEXT_PUBLIC_SITE_ENV = "staging"
  NEXT_PUBLIC_SITE_URL = "https://staging.pinga.photos"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "frame-ancestors https://app.storyblok.com"
